# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 15:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_type', models.CharField(blank=True, max_length=30, verbose_name='nikkon')),
                ('address', models.CharField(blank=True, max_length=60, verbose_name='address')),
                ('web_link', models.CharField(blank=True, max_length=70, verbose_name='personal site')),
                ('photo_type', models.CharField(blank=True, max_length=30, verbose_name='nature')),
                ('social_media', models.CharField(blank=True, max_length=30, verbose_name='handle')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
    ]
