# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-20 06:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('camera_type', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=60)),
                ('web_link', models.CharField(blank=True, max_length=70)),
                ('photo_type', models.CharField(blank=True, max_length=30)),
                ('social_media', models.CharField(blank=True, max_length=30)),
                ('region', models.CharField(choices=[('North America', 'North America'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('South America', 'South America'), ('Europe', 'Europe')], default='North America', max_length=30)),
                ('friends', models.ManyToManyField(related_name='friend_of', to='imager_profile.UserProfile')),
            ],
        ),
    ]
