# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 20:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20160411_1158'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
