# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0005_auto_20160411_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='friends',
            field=models.ManyToManyField(related_name='friend_of', to='imager_profile.UserProfile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(choices=[('North America', 'North America'), ('Asia', 'Asia'), ('Africa', 'Africa'), ('South America', 'South America'), ('Europe', 'Europe')], default='North America', max_length=30),
        ),
    ]
