# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0006_auto_20160412_0932'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
    ]
