# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_of', to='imager_images.Photo'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to='bob'),
        ),
    ]
