# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0003_auto_20160412_1017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user',
            new_name='owner',
        ),
    ]
