# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:58
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0004_auto_20160412_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='published',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared')], default='private', max_length=30),
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_file',
            field=models.ImageField(upload_to=imager_images.models._image_path),
        ),
        migrations.AlterField(
            model_name='photo',
            name='published',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('shared', 'Shared')], default='private', max_length=30),
        ),
    ]
