# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 02:35
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0005_auto_20160412_1758'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='photo',
            managers=[
                ('public', django.db.models.manager.Manager()),
            ],
        ),
    ]
